# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  broadcast-app:
    image: broadcast
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:broadcast;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_LIQUIBASE_URL=jdbc:h2:mem:broadcast;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
